# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(1e0ab535-a9e6-41d3-bede-c3b737c9232c)'
    subscriptionId: '1e0ab535-a9e6-41d3-bede-c3b737c9232c'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'JavaTest-Lab'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/robanstee/pipelines-java/main/pipelines-java-tutorial-webapp/template.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/robanstee/pipelines-java/main/pipelines-java-tutorial-webapp/parameters.json'
    deploymentMode: 'Incremental'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(1e0ab535-a9e6-41d3-bede-c3b737c9232c)'
    appType: 'webAppLinux'
    appName: 'pipelines-java-tutorial'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'